export const PROUDUCT_LIST_REQUEST = 'PROUDUCT_LIST_REQUEST'
export const PROUDUCT_LIST_SUCCESS = 'PROUDUCT_LIST_SUCCESS'
export const PROUDUCT_LIST_FAIL = 'PROUDUCT_LIST_FAIL'

export const PROUDUCT_DETAILS_REQUEST = 'PROUDUCT_DETAILS_REQUEST'
export const PROUDUCT_DETAILS_SUCCESS = 'PROUDUCT_DETAILS_SUCCESS'
export const PROUDUCT_DETAILS_FAIL = 'PROUDUCT_DETAILS_FAIL'
